name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          if [ -d "pr-${{ github.event.pull_request.number }}" ]; then
            rm -rf pr-${{ github.event.pull_request.number }}
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
            git push origin gh-pages
          else
            echo "Preview directory not found, nothing to clean up"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## 🧹 Preview Cleanup\n\nThe preview deployment for this PR has been removed.`
            });
